# Dicionário do workbook. Uma linha por coluna de cada aba; novos campos sem
# definição interrompem a exportação, para não publicar um dicionário incompleto.

cria_dicionario_campos = function(dados_abas) {
  definicoes = c(
    Fundo = "Fundo identificado na linha da matriz de correlação.",
    adjusted_rand = "Índice de Rand ajustado entre duas partições de clusters; 1 indica concordância perfeita.",
    alertas_relativos = "Alertas de drawdown ou cauda entre os 10% piores da amostra; não são vetos.",
    aprovado_quantitativo = "Indica aprovação com margem pela régua quantitativa.",
    autocorrelacao_lag1 = "Correlação do excesso mensal com o excesso do mês anterior.",
    benchmark = "Índice comparativo usado na análise de afinidade.",
    benchmark_maior_correlacao = "Benchmark com maior correlação de excessos mensais com o fundo.",
    benchmark_menor_tracking_error = "Benchmark com menor dispersão do retorno relativo mensal ao fundo.",
    classificacao_descritiva = "Classificação descritiva da posição no ranking; não define aprovação.",
    cluster = "Grupo atribuído no diagnóstico para o número de clusters indicado por k.",
    correlacao = "Correlação amostral entre as duas séries indicadas na mesma linha.",
    correlacao_maxima = "Maior correlação observada entre o fundo e seus pares no diagnóstico.",
    correlacao_maxima_carteira = "Maior correlação entre o candidato e um fundo cadastrado na carteira atual.",
    correlacao_media_intercluster = "Média das correlações entre fundos de clusters distintos.",
    correlacao_media_intracluster = "Média das correlações entre fundos do mesmo cluster.",
    correlacao_media_pares = "Média das correlações do fundo com os demais pares elegíveis.",
    correlacao_mediana_pares = "Mediana das correlações do fundo com os demais pares elegíveis.",
    criterio_priorizacao = "Motivo específico da entrada do fundo na fila de diligência.",
    data_fim_score = "Último mês da janela comum usada no score.",
    data_inicio_intervalo = "Data anterior à primeira cota usada para compor o retorno mensal.",
    data_inicio_intervalo_esperada = "Data esperada para início do intervalo segundo o calendário do CDI.",
    data_inicio_score = "Primeiro mês da janela comum usada no score.",
    decisao = "Regra ou escolha metodológica descrita pelo item da mesma linha.",
    defasagem_meses = "Deslocamento, em meses, empregado no teste de estabilidade dos clusters.",
    dias_sem_cdi_no_fim = "Dias corridos entre a última observação do CDI e o fim do mês calendário.",
    elegivel_ranking = "Indica que o fundo satisfaz a janela e possui métricas finitas para ranqueamento.",
    elegivel_score_36m = "Indica 36 meses completos e comuns para cálculo do score.",
    envolve_carteira_atual = "Indica que ao menos um fundo do par consta no cadastro da carteira atual.",
    estatistica = "Nome da estatística resumida na distribuição das correlações.",
    excesso_benchmark_aa = "Retorno relativo geométrico ao benchmark, anualizado nos meses comparados.",
    excesso_cdi_aa = "Excesso geométrico anualizado sobre o CDI nos 36 meses comuns: [produto(1 + excesso_cdi_m)]^(12/36) - 1. Não é spread de crédito nem diferença simples entre taxas anualizadas.",
    excesso_cdi_acumulado = "Excesso relativo ao CDI acumulado geometricamente até o mês indicado.",
    excesso_cdi_m = "Excesso geométrico mensal: (1 + retorno mensal do fundo)/(1 + retorno mensal do CDI) - 1.",
    fim_historico_mensal = "Último mês válido do histórico mensal completo do fundo.",
    fim_serie_diaria = "Última data com retorno diário válido do fundo.",
    fim_serie_mensal_score = "Último mês válido do fundo dentro da janela do score.",
    fundo_a = "Primeiro fundo do par de correlação.",
    fundo_a_carteira = "Indica se o primeiro fundo do par consta na carteira cadastrada.",
    fundo_b = "Segundo fundo do par de correlação.",
    fundo_b_carteira = "Indica se o segundo fundo do par consta na carteira cadastrada.",
    fundo_carteira_mais_correlacionado = "Posição cadastrada na carteira atual com maior correlação com o candidato.",
    fundo_mais_correlacionado = "Fundo do universo com maior correlação com o fundo da linha.",
    hit_rate_12m = "Fração das janelas móveis de 12 meses com excesso composto positivo sobre CDI.",
    hit_rate_36m_historico = "Fração das janelas históricas completas de 36 meses com excesso composto positivo.",
    hit_rate_6m = "Fração das janelas móveis de 6 meses com excesso composto positivo sobre CDI.",
    hit_rate_mensal = "Fração dos meses com retorno relativo positivo à referência indicada na aba.",
    inicio_historico_mensal = "Primeiro mês válido do histórico mensal completo do fundo.",
    inicio_serie_diaria = "Primeira data com retorno diário válido do fundo.",
    inicio_serie_mensal_score = "Primeiro mês válido do fundo dentro da janela do score.",
    item = "Tema da escolha metodológica registrada na mesma linha.",
    k = "Número de clusters considerado no diagnóstico.",
    limiar = "Valor de correlação testado para contagem de pares redundantes.",
    maior_cluster = "Número de fundos no maior cluster da solução k.",
    maior_correlacao = "Maior correlação do fundo com um dos benchmarks comparados.",
    max_drawdown_excesso = "Maior queda do índice acumulado de excesso sobre CDI desde um pico anterior.",
    media_tres_piores_meses = "Média dos três piores excessos mensais sobre CDI na janela do score.",
    menor_cluster = "Número de fundos no menor cluster da solução k.",
    menor_tracking_error_aa = "Menor desvio-padrão anualizado do retorno relativo aos benchmarks comparados.",
    mes = "Mês de referência da observação mensal.",
    mes_completo = "Indica que o mês atende às verificações de cobertura e sequência de cotas e CDI.",
    mes_encerrado = "Indica que o mês pode ser tratado como encerrado no calendário de dados.",
    mes_fim = "Último mês da janela usada no diagnóstico.",
    mes_seguinte_observado = "Indica presença de observação no mês posterior, usada para fechar o mês atual.",
    meses_em_comum_com_par_mais_proximo = "Meses válidos em comum com o fundo de maior correlação.",
    meses_para_recuperar = "Meses até recuperação do pior drawdown relativo; ausente se não houve recuperação.",
    metrica = "Nome do indicador de diagnóstico apresentado na mesma linha.",
    motivo_inelegibilidade = "Razão da ausência de score na janela comum de 36 meses.",
    n_cdi_validos = "Número de datas com retorno do CDI válido no mês.",
    n_datas_cdi = "Número esperado de datas de CDI no mês.",
    n_fundos_janela = "Quantidade de fundos presentes na janela do teste de estabilidade.",
    n_intervalos_invalidos = "Número de intervalos entre cotas que não correspondem a um dia útil.",
    n_janelas_36m_historico = "Número de janelas completas e consecutivas de 36 meses no histórico.",
    n_meses = "Número de meses válidos da série considerada na aba.",
    n_meses_completos = "Número de meses completos segundo os critérios de integridade.",
    n_meses_historico = "Número de meses válidos no histórico mensal completo.",
    n_meses_score = "Número de meses válidos dentro da janela comum do score.",
    n_obs = "Número de observações diárias do fundo no mês.",
    n_pares = "Quantidade de pares de fundos que alcançam o limiar de correlação.",
    n_pares_com_carteira = "Quantidade de pares acima do limiar com ao menos um fundo da carteira cadastrada.",
    n_retornos_diarios = "Número de retornos diários válidos do fundo.",
    nivel_redundancia = "Faixa diagnóstica da correlação do par: atenção, elevada ou muito elevada.",
    nivel_redundancia_carteira = "Faixa diagnóstica da maior correlação com posição cadastrada.",
    nivel_redundancia_maxima = "Faixa diagnóstica da maior correlação do fundo com qualquer par.",
    nome_curto = "Nome curto do fundo usado para leitura.",
    nome_plot = "Nome padronizado do fundo usado no ranking e nos gráficos.",
    nome_quantum = "Nome da série correspondente na base Quantum.",
    nome_xlsx = "Identificador do fundo herdado do cadastro original; permanece como chave interna.",
    nota_consistencia = "Nota do pilar de consistência, de 0 a 100.",
    nota_custo = "Nota do pilar de custo observável, de 0 a 100.",
    nota_final = "Média ponderada dos pilares: retorno 30%, consistência 25%, risco 20% e custo 25%.",
    nota_minima_pilar = "Menor nota entre retorno, consistência, risco e custo.",
    nota_razao_excesso_taxa = "Nota robusta da razão entre excesso líquido anualizado e taxa de administração.",
    nota_retorno = "Nota do pilar de retorno, de 0 a 100.",
    nota_risco = "Nota do pilar de risco, de 0 a 100.",
    nota_taxa = "Nota robusta da taxa de administração; taxa menor recebe nota maior.",
    observacao_qualitativa = "Observação registrada manualmente na avaliação qualitativa.",
    pilar_abaixo_minimo = "Indica que alguma nota de pilar ficou abaixo do piso de 30.",
    pior_mes = "Menor excesso mensal sobre CDI observado na janela do score.",
    primeira_data = "Primeira data de cota observada no mês.",
    primeira_data_cdi = "Primeira data de CDI observada no mês.",
    primeiro_mes = "Primeiro mês disponível do fundo no histórico.",
    prioridade_analise_qualitativa = "Ordem de diligência entre aprovados quantitativos e casos da fronteira.",
    quartil = "Quartil descritivo do score associado à trajetória histórica.",
    quartil_score = "Quartil descritivo da nota final entre fundos elegíveis.",
    ranking_geral = "Posição decrescente da nota final entre os fundos elegíveis.",
    razao_excesso_taxa = "Excesso líquido anualizado sobre CDI dividido pela taxa de administração anual.",
    red_flags_absolutos = "Motivo de veto quantitativo absoluto; nesta versão, excesso anualizado não positivo.",
    ret_cdi_m = "Retorno geométrico do CDI no mês.",
    ret_fundo_m = "Retorno geométrico da cota ajustada do fundo no mês.",
    ret_ida_di_m = "Retorno geométrico mensal do IDA-DI.",
    ret_ida_liq_di_m = "Retorno geométrico mensal do IDA LIQ-DI.",
    ret_irfm_1_m = "Retorno geométrico mensal do IRF-M 1.",
    revisar = "Indica correspondência de nome/cadastro que requer revisão manual.",
    silhueta_media = "Média dos coeficientes de silhueta da solução de clusters.",
    status_priorizacao = "Estado da fila de diligência, calculado após a régua quantitativa.",
    status_qualitativo = "Conclusão qualitativa registrada manualmente; vazio não significa aprovação.",
    status_quantitativo = "Classificação pela régua de aprovação, fronteira e red flag.",
    taxa_adm_aa = "Taxa anual de administração do cadastro; fração decimal, sem performance ou taxa da casa.",
    taxa_requer_revisao = "Alerta de taxa extrema pelo z robusto do log da taxa; não entra no score como veto.",
    tipo_par = "Categoria do par: candidatos, posições atuais ou candidato versus posição atual.",
    tracking_error_aa = "Desvio-padrão anualizado do retorno relativo mensal do fundo ao benchmark.",
    ultima_data = "Última data de cota observada no mês.",
    ultima_data_cdi = "Última data de CDI observada no mês.",
    ultimo_dia_calendario = "Último dia calendário do mês.",
    ultimo_mes = "Último mês disponível do fundo no histórico.",
    valor = "Valor da estatística ou métrica nomeada na mesma linha; unidade depende do indicador.",
    volatilidade_excesso_aa = "Desvio-padrão dos excessos mensais sobre CDI multiplicado por raiz de 12.",
    z_robusto_log_taxa = "Distância robusta do log da taxa de administração à mediana das taxas.",
    zona_fronteira = "Indica nota de 52 a menos de 58, ou nota maior com pilar abaixo de 30."
  )

  descricoes = purrr::imap_dfr(dados_abas, function(dados, aba) {
    campos = names(dados)
    matriz_fundo = aba == "Matriz Correlação" & campos != "Fundo"
    definicao = unname(definicoes[campos])
    definicao[matriz_fundo] = paste0(
      "Correlação dos excessos mensais do fundo na linha com ",
      campos[matriz_fundo], ", na janela comum de 36 meses."
    )

    tibble(
      aba = aba,
      campo = campos,
      definicao = definicao,
      unidade = case_when(
        matriz_fundo ~ "Correlação (-1 a 1)",
        str_detect(campos, "^(nota_|nota_final$)") ~ "Pontos (0 a 100)",
        str_detect(campos, "^(n_|k$|menor_cluster$|maior_cluster$|defasagem_meses$|dias_sem_cdi_no_fim$|meses_)") ~ "Contagem",
        str_detect(campos, "^(ret_|excesso_|hit_rate|volatilidade|drawdown|max_drawdown|pior_mes|media_tres|taxa_adm|tracking_error|menor_tracking_error)") ~ "Percentual",
        str_detect(campos, "(correlacao|silhueta|adjusted_rand|z_robusto|razao_excesso_taxa|limiar)") ~ "Razão ou correlação",
        str_detect(campos, "(^data|_data$|^primeira_data$|^ultima_data$|^mes$|^mes_fim$|_mes$|^primeiro_mes$|^ultimo_mes$|^inicio_|^fim_)") ~ "Data ou mês",
        campos == "valor" ~ "Conforme indicador",
        campos %in% c("aprovado_quantitativo", "zona_fronteira", "pilar_abaixo_minimo", "elegivel_ranking", "elegivel_score_36m", "envolve_carteira_atual", "fundo_a_carteira", "fundo_b_carteira", "mes_completo", "mes_encerrado", "mes_seguinte_observado", "revisar", "taxa_requer_revisao") ~ "Sim/Não",
        TRUE ~ "Texto ou categoria"
      ),
      periodo = case_when(
        aba == "Histórico Mensal" ~ "Mês indicado; histórico completo",
        str_detect(campos, "historico|janelas_36m") ~ "Histórico completo",
        aba %in% c("Metodologia", "Diagnóstico Taxas") ~ "Parâmetros da rodada",
        aba == "Estab. Clusters" ~ "Janelas históricas do teste",
        TRUE ~ "Rodada e 36 meses comuns"
      ),
      papel = case_when(
        aba == "Ranking" ~ "Score, classificação ou diligência",
        aba == "Todos os Fundos" ~ "Cobertura, elegibilidade ou métrica",
        aba %in% c("Pares Redundância", "Sensib. Redundância", "Distrib. Correlações", "Matriz Correlação") ~ "Diagnóstico de redundância; não entra no score",
        str_detect(aba, "Clusters") ~ "Diagnóstico de clusters; não entra no score",
        aba == "Histórico Mensal" ~ "Auditoria e diagnóstico mensal",
        aba == "Metodologia" ~ "Parâmetro ou regra",
        TRUE ~ "Diagnóstico complementar"
      )
    )
  })

  sem_definicao = descricoes %>% filter(is.na(definicao) | definicao == "")
  if (nrow(sem_definicao) > 0) {
    stop(
      "Campos sem definição no dicionário: ",
      paste(unique(sem_definicao$campo), collapse = ", ")
    )
  }

  descricoes
}
