---
title: "desempenho-ativos"
format: 
  pptx:
    reference-doc: /Dados/modelo.pptx
editor: visual
---

```{r Pacotes, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}

library(tidyverse)
library(GetTDData)
library(mFilter)
library(sidrar)
library(rbcb)
library(rb3)

```

```{r Setup, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}

rm(list = ls())

Sys.setenv("LANGUAGE" = "Pt")
Sys.setlocale("LC_ALL", "Portuguese")

```

```{r Coleta de dados, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}

# expectativas

annual = get_market_expectations(type = "annual",
                                 start_date = Sys.Date() - 360)

monthly = get_market_expectations(type  = "monthly",
                                  start_date = Sys.Date() - 360)

selic = get_market_expectations(type = "selic",
                                start_date = Sys.Date() - 360)

inflation_twelve_months = get_market_expectations(type = "inflation-12-months",
                                                  start_date = Sys.Date() - 360)

# dados complementares

ipca_target <- get_series(code = c("Meta" = 13521)) %>% 
  mutate(DataReferencia  = as.character(year(date)),
         .keep = "unused",
         .before = "Meta") %>%
  add_row(DataReferencia = c("2025","2026","2027"), Meta = c(3,3,3))

yc = yc_get(refdate = max(selic$Data))

ipca = get_sidra(x = 1737, api = '/t/1737/n1/all/v/2265/p/all/d/v2265%202') %>%
  mutate(date = parse_date(`Mês (Código)`, format = '%Y%m')) %>%
  select(date, Valor) %>%
  `colnames<-`(c("date",
                 "ipca")) %>%
  filter(date >= "2001-01-01") %>%
  as_tibble()

juros = get_series(code = 432, start_date = "2001-01-01") %>%
  `colnames<-`(c("date",
                 "selic"))

exp_ipca <- get_twelve_months_inflation_expectations('IPCA') %>%
  filter(base == 0, smoothed == "S") %>%
  select(date, median) %>%
  `colnames<-`(c("date",
                 "exp_ipca"))

swap <- ipeadatar::ipeadata(code = "BMF12_SWAPDI36012") %>%
  select(date, value) %>%
  `colnames<-`(c("date",
                 "swap"))

ntnb <- td_get('NTN-B')


```

```{r Tratamento de dados, echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}

annual_df = annual %>% 
  filter(DataReferencia    == year(Sys.Date())     |
           DataReferencia    == year(Sys.Date()) + 1 | 
           DataReferencia    == year(Sys.Date()) + 2 | 
           DataReferencia    == year(Sys.Date()) + 3,
         baseCalculo       == 0,
         !IndicadorDetalhe %in% c("Exportações", "Importações")) %>% 
  select(everything(), -c(2,11)) %>% 
  pivot_longer(cols = c(4:9))

selic_df = selic %>%
  separate(Reuniao, into = c("reuniao_mes", "reuniao_ano"), sep = "/") %>%
  mutate(mes = case_when(reuniao_mes == "R1" ~"01",
                         reuniao_mes == "R2" ~"03",
                         reuniao_mes == "R3" ~"04",
                         reuniao_mes == "R4" ~"06",
                         reuniao_mes == "R5" ~"08",
                         reuniao_mes == "R6" ~"09",
                         reuniao_mes == "R7" ~"11",
                         reuniao_mes == "R8" ~"12"),
         DataReferencia = lubridate::dmy(paste0("01/", mes,"/", reuniao_ano))) %>%
  filter(baseCalculo == 0)

juro_expost <- merge(juros, ipca, all = TRUE) %>%
  zoo::na.locf() %>%
  mutate(ex_post = (((1 + (selic/100))/(1 + (ipca/100))) - 1) * 100) %>%
  as_tibble()

juro_exante <- merge(swap, exp_ipca, all = TRUE) %>%
  zoo::na.locf() %>%
  mutate(ex_ante = (((1 + (swap/100))/(1 + (exp_ipca/100))) - 1) * 100) %>%
  as_tibble()

ntnb45 <- ntnb %>%
  filter(asset_code  == "NTN-B 150545")

juro_ntnb <- ntnb45[,c(1,2)] %>%
  mutate(yield_bid = yield_bid*100) %>%
  rename(date = ref_date)

df_juros <- merge(juro_exante, juro_expost, all = TRUE)[, c(1,4,7)] %>%
  filter(date >= "2005-01-03")

df_juros <- merge(df_juros, juro_ntnb, all = TRUE)

df_juros <- df_juros[complete.cases(df_juros),]
df_juros <- data.frame(date = df_juros[,1], ex_ante = df_juros[,2],
                ex_post = df_juros[,3], neutro = df_juros[,4])

df_juros <- df_juros %>%
  mutate(date = floor_date(date, "month")) %>%
  group_by(date) %>%
  summarise(
    ex_ante = mean(ex_ante, na.rm = TRUE),
    ex_post = mean(ex_post, na.rm = TRUE),
    neutro  = mean(neutro, na.rm = TRUE))

df_juros$neutro <- hpfilter(df_juros$neutro, freq = 14400, type = 'lambda')$trend
```

# Sumário

```{r Sumario, echo = FALSE, fig.width=8, fig.height=6, fig.align='center'}

annual_df %>% 
  filter(name == "Mediana",
         Indicador %in% c("IPCA", 
                          "PIB Total", 
                          "Câmbio", 
                          "Selic")) %>%
  ggplot() +
  aes(x = Data, y = value, color = DataReferencia) +
  geom_line(linewidth = 1) +
  theme_bw() + theme(panel.grid.minor = element_blank(), 
                     legend.position  = "bottom", 
                     legend.title     = element_blank(),
                     axis.line        = element_line(colour = "black"),
                     axis.text.x      = element_text(angle = 90), 
                     axis.title       = element_blank()) + 
  facet_wrap(~Indicador, scales = "free_y", nrow = 2) +
  scale_x_date(expand = c(0,0), date_labels = "%m/%y", date_breaks = "30 days",) +
  scale_colour_manual(values = c("#4e5579", 
                                 "#4eadde",
                                 "#dc7a3a",
                                 "#a74b2d")) + 
  labs(title = "Relatório Focus", caption = "Fonte: Banco Central do Brasil")

```

# Juros

```{r Juros, echo = FALSE, fig.width=8, fig.height=6, fig.align='center'}

selic_df %>% 
  filter(Data == max(Data)) %>% 
  ggplot() + 
  geom_ribbon(aes(DataReferencia, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
  geom_line(aes(x = DataReferencia, y = Media,   color = "Média"), linewidth = .75) +
  geom_line(data = filter(yc, forward_date <= max(selic_df$DataReferencia)), aes(x = forward_date, y = r_252*100, color = "ETTJ"), linewidth = .75) +
  geom_line(aes(x = DataReferencia, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
  geom_line(aes(x = DataReferencia, y = Maximo,  color = "Máximo")) +
  geom_line(aes(x = DataReferencia, y = Minimo,  color = "Mínimo")) +
  theme_bw() + theme(panel.grid.minor = element_blank(), 
                     legend.position  = "bottom", 
                     legend.title     = element_blank(),
                     axis.line        = element_line(colour = "black"),
                     axis.text.x      = element_text(angle = 90), 
                     axis.title       = element_blank()) + 
  # facet_wrap(~year(DataReferencia), scales  = "free_y", nrow = 2) +
  scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
  scale_colour_manual(values = c("Média" = "#4e5579",
                                 "ETTJ" = "black",
                                 "Mediana" = "red",
                                 "Máximo" = "darkred",
                                 "Mínimo" = "darkred")) +
  scale_fill_manual(values = c("Desvio Padrão" = "#4eadde")) +
  guides(fill = guide_legend(ncol = 1),
         colour = guide_legend(ncol = 3)) +
  labs(title = "Trajetória esperada da Taxa Selic", caption = "Fonte: Banco Central do Brasil")

df_juros %>%
  pivot_longer(cols = -date,
               names_to = "desc",
               values_to = "values") %>%
  ggplot() +
  aes(date, values[,1], color = desc) +
  geom_line(linewidth = .75) +
  theme_bw() + theme(panel.grid.minor = element_blank(),
                     axis.line = element_line(colour = "black"),
                     legend.title = element_blank(),
                     axis.title = element_blank(),
                     strip.background = element_blank()) +
  scale_colour_manual(values = c("#2F47AD",
                                 "#31AFE0",
                                 "#E47632"),
                      labels = c("ex_ante" = "Ex-ante",
                                 "ex_post" = "Ex-post",
                                 "neutro" = "Juro Neutro")) +
  scale_x_date(expand = c(0,0), date_labels = "%Y", breaks = "12 months") +
  labs(title = NULL,
       subtitle = "Taxa Neutra implícita de mercado, Ex-Ante e Ex-Post")



```

# Inflação

```{r Inflacao, echo = FALSE, fig.width=6, fig.height=4, fig.align='center'}

pi = c("IPCA", 
       "IPCA Administrados",
       "IPCA Livres",
       "IPCA Alimentação no domicílio",
       "IPCA Bens industrializados",
       "IPCA Serviços",
       "IGP-M")

# graphs
for (i in pi) {
  
  print(
    left_join(annual_df, ipca_target, by = "DataReferencia") %>% 
      filter(Indicador == i,
             !name %in% c("numeroRespondentes")) %>%
      pivot_wider() %>% 
      ggplot() + 
      geom_ribbon(aes(Data, ymax = Meta + 1.5, ymin = Meta - 1.5, fill = "Intervalo da meta"), alpha = 0.3) +
      geom_line(aes(x = Data, y = Meta, color = "Meta"), linewidth = .75, linetype = "dotted") +
      geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
      geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
      geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
      geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
      geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "bottom", 
                         legend.title     = element_blank(),
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
      scale_colour_manual(values = c("Média" = "#4e5579",
                                     "Meta" = "black",
                                     "Mediana" = "red",
                                     "Máximo" = "darkred",
                                     "Mínimo" = "darkred")) +
      scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                                   "Intervalo da meta" = "darkgray")) +
      guides(fill = guide_legend(ncol = 1),
             colour = guide_legend(ncol = 3)) +
      labs(title = i)
  )
  
  # n respondentes
  
  print(
    annual_df %>% 
      filter(Indicador  == i,
             name == "numeroRespondentes") %>%
      ggplot() +
      aes(x = Data, y = value) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")
  )
  
}
```

# Atividade

```{r Atividade, echo = FALSE, fig.width=6, fig.height=4, fig.align='center'}

annual_df %>%
  filter(Indicador == "Taxa de desocupação",
         !name %in% c("numeroRespondentes")) %>%
  pivot_wider() %>% 
  ggplot() + 
  geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
  geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
  geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
  geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
  geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
  theme_bw() + theme(panel.grid.minor = element_blank(), 
                     legend.position  = "bottom", 
                     legend.title     = element_blank(),
                     axis.line        = element_line(colour = "black"),
                     axis.text.x      = element_text(angle = 90), 
                     axis.title       = element_blank()) + 
  facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
  scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
  scale_colour_manual(values = c("Média" = "#4e5579",
                                 "Tendência" = "black",
                                 "Mediana" = "red",
                                 "Máximo" = "darkred",
                                 "Mínimo" = "darkred")) +
  scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                               "Intervalo da meta" = "darkgray")) +
  guides(fill = guide_legend(ncol = 1),
         colour = guide_legend(ncol = 3)) +
  labs(title = "Taxa de desocupação")

annual_df %>% 
      filter(Indicador  == "Taxa de desocupação",
             name == "numeroRespondentes") %>%
      ggplot() +
      aes(x = Data, y = value) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")

annual_df %>% 
  add_column(Trend = 2.5) %>% 
  filter(Indicador == "PIB Total",
         !name %in% c("numeroRespondentes")) %>%
  pivot_wider() %>% 
  ggplot() + 
  geom_line(aes(x = Data, y = Trend, color = "Tendência"), linewidth = .75, linetype = "dotted") +
  geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
  geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
  geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
  geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
  geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
  theme_bw() + theme(panel.grid.minor = element_blank(), 
                     legend.position  = "bottom", 
                     legend.title     = element_blank(),
                     axis.line        = element_line(colour = "black"),
                     axis.text.x      = element_text(angle = 90), 
                     axis.title       = element_blank()) + 
  facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
  scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
  scale_colour_manual(values = c("Média" = "#4e5579",
                                 "Tendência" = "black",
                                 "Mediana" = "red",
                                 "Máximo" = "darkred",
                                 "Mínimo" = "darkred")) +
  scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                               "Intervalo da meta" = "darkgray")) +
  guides(fill = guide_legend(ncol = 1),
         colour = guide_legend(ncol = 3)) +
  labs(title = "PIB")

annual_df %>% 
      filter(Indicador == "PIB Total",
             name == "numeroRespondentes") %>%
      ggplot() +
      aes(x = Data, y = value) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")

y = c("PIB Agropecuária",
       "PIB Indústria",
       "PIB Serviços",
       "PIB Despesa de consumo das famílias",
       "PIB Formação Bruta de Capital Fixo",
       "PIB Despesa de consumo da administração pública",
       "PIB Exportação de bens e serviços",
       "PIB Importação de bens e serviços")

# graphs
for (i in y) {
  
  print(
    annual_df %>% 
      filter(Indicador == i,
             !name %in% c("numeroRespondentes")) %>%
      pivot_wider() %>% 
      ggplot() + 
      geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
      geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
      geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
      geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
      geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "bottom", 
                         legend.title     = element_blank(),
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
      scale_colour_manual(values = c("Média" = "#4e5579",
                                     "Meta" = "black",
                                     "Mediana" = "red",
                                     "Máximo" = "darkred",
                                     "Mínimo" = "darkred")) +
      scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                                   "Intervalo da meta" = "darkgray")) +
      guides(fill = guide_legend(ncol = 1),
             colour = guide_legend(ncol = 3)) +
      labs(title = i)
  )
  
  # n respondentes
  
  print(
    annual_df %>% 
      filter(Indicador  == i,
             name == "numeroRespondentes") %>%
      ggplot() +
      aes(x = Data, y = value) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")
  )
}

```

# Câmbio

```{r Cambio, echo = FALSE, fig.width=6, fig.height=4, fig.align='center'}

annual_df %>% 
  filter(Indicador == "Câmbio",
         !name %in% c("numeroRespondentes")) %>%
  pivot_wider() %>% 
  ggplot() + 
  geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
  geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
  geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
  geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
  geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
  theme_bw() + theme(panel.grid.minor = element_blank(), 
                     legend.position  = "bottom", 
                     legend.title     = element_blank(),
                     axis.line        = element_line(colour = "black"),
                     axis.text.x      = element_text(angle = 90), 
                     axis.title       = element_blank()) + 
  facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
  scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
  scale_colour_manual(values = c("Média" = "#4e5579",
                                 "Tendência" = "black",
                                 "Mediana" = "red",
                                 "Máximo" = "darkred",
                                 "Mínimo" = "darkred")) +
  scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                               "Intervalo da meta" = "darkgray")) +
  guides(fill = guide_legend(ncol = 1),
         colour = guide_legend(ncol = 3)) +
  labs(title = "Câmbio")

annual_df %>% 
  filter(Indicador  == "Câmbio",
         name == "numeroRespondentes") %>%
  ggplot() +
  aes(x = Data, y = value) +
  geom_bar(stat = "identity", fill = "#4e5579") +
  # geom_line() +
  theme_bw() + theme(panel.grid.minor = element_blank(), 
                     legend.position  = "none", 
                     axis.line        = element_line(colour = "black"),
                     axis.text.x      = element_text(angle = 90), 
                     axis.title       = element_blank()) + 
  facet_wrap(~DataReferencia, nrow = 2) +
  scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
  labs(subtitle = "Número de respondentes")

```

# Contas Externas

```{r Contas_Externas, echo = FALSE, fig.width=6, fig.height=4, fig.align='center'}

bp = c("Balança comercial",
       "Conta corrente",
       "Investimento direto no país")

for (i in bp) {
  
  print(
    annual_df %>% 
      filter(Indicador == i,
             !name %in% c("numeroRespondentes")) %>%
      pivot_wider() %>% 
      ggplot() + 
      geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
      geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
      geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
      geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
      geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "bottom", 
                         legend.title     = element_blank(),
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
      scale_colour_manual(values = c("Média" = "#4e5579",
                                     "Meta" = "black",
                                     "Mediana" = "red",
                                     "Máximo" = "darkred",
                                     "Mínimo" = "darkred")) +
      scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                                   "Intervalo da meta" = "darkgray")) +
      guides(fill = guide_legend(ncol = 1),
             colour = guide_legend(ncol = 3)) +
      labs(title = paste0(i, " (US$ bilhões)"))
  )
  
  # n respondentes
  
  print(
    annual_df %>% 
      filter(Indicador  == i,
             name == "numeroRespondentes") %>%
      ggplot() +
      aes(x = Data, y = value) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")
  )
  
}

```

# Contas Públicas

```{r Contas_Publicas, echo = FALSE, fig.width=6, fig.height=4, fig.align='center'}

g = c("Resultado primário",
      "Resultado nominal",
      "Dívida bruta do governo geral",
      "Dívida líquida do setor público")

for (i in g) {
  
  print(
    annual_df %>% 
      filter(Indicador == i,
             !name %in% c("numeroRespondentes")) %>%
      pivot_wider() %>% 
      ggplot() + 
      geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
      geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
      geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
      geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
      geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "bottom", 
                         legend.title     = element_blank(),
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, scales  = "free_y", nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
      scale_colour_manual(values = c("Média" = "#4e5579",
                                     "Meta" = "black",
                                     "Mediana" = "red",
                                     "Máximo" = "darkred",
                                     "Mínimo" = "darkred")) +
      scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                                   "Intervalo da meta" = "darkgray")) +
      guides(fill = guide_legend(ncol = 1),
             colour = guide_legend(ncol = 3)) +
      labs(title = paste0(i, " (% do PIB)"))
  )
  
  # n respondentes
  
  print(
    annual_df %>% 
      filter(Indicador  == i,
             name == "numeroRespondentes") %>%
      ggplot() +
      aes(x = Data, y = value) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")
    )

  
}

```

# Séries mensais

```{r Mensais, echo = FALSE, fig.width=6, fig.height=4, fig.align='center'}

for (i in unique(monthly$Indicador)) {
  
  print(
    monthly %>% 
      separate(DataReferencia, into = c("mes", "ano"), sep = "/") %>%
      mutate(DataReferencia = lubridate::dmy(paste0("01/", mes,"/", ano))) %>%
      filter(Indicador == i,
             baseCalculo == 0,
             ano == year(Sys.Date()),
             month(DataReferencia) %in% c(month(Sys.Date()) + 1, month(Sys.Date()) + 2, month(Sys.Date()) + 3, month(Sys.Date()) + 4)) %>% 
      ggplot() + 
      geom_ribbon(aes(Data, ymax = Media + DesvioPadrao, ymin = Media - DesvioPadrao, fill = "Desvio Padrão"), alpha = 0.6) +
      geom_line(aes(x = Data, y = Media,   color = "Média"), linewidth = .75) +
      geom_line(aes(x = Data, y = Mediana, color = "Mediana"), linewidth = .75, linetype = "dashed") +
      geom_line(aes(x = Data, y = Maximo,  color = "Máximo")) +
      geom_line(aes(x = Data, y = Minimo,  color = "Mínimo")) +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "bottom", 
                         legend.title     = element_blank(),
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~mes, scales  = "free_y", nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days",) +
      scale_colour_manual(values = c("Média" = "#4e5579",
                                     "Meta" = "black",
                                     "Mediana" = "red",
                                     "Máximo" = "darkred",
                                     "Mínimo" = "darkred")) +
      scale_fill_manual(values = c("Desvio Padrão" = "#4eadde",
                                   "Intervalo da meta" = "darkgray")) +
      guides(fill = guide_legend(ncol = 1),
             colour = guide_legend(ncol = 3)) +
      labs(title = paste0(i, " Mensal"))
  )
  
  # n respondentes
  
  print(
    monthly %>% 
      separate(DataReferencia, into = c("mes", "ano"), sep = "/") %>%
      mutate(DataReferencia = lubridate::dmy(paste0("01/", mes,"/", ano))) %>%
      filter(Indicador == i,
             baseCalculo == 0,
             ano == year(Sys.Date()),
             month(DataReferencia) %in% c(month(Sys.Date()) + 1, month(Sys.Date()) + 2, month(Sys.Date()) + 3, month(Sys.Date()) + 4)) %>% 
      ggplot() +
      aes(x = Data, y = numeroRespondentes) +
      geom_bar(stat = "identity", fill = "#4e5579") +
      # geom_line() +
      theme_bw() + theme(panel.grid.minor = element_blank(), 
                         legend.position  = "none", 
                         axis.line        = element_line(colour = "black"),
                         axis.text.x      = element_text(angle = 90), 
                         axis.title       = element_blank()) + 
      facet_wrap(~DataReferencia, nrow = 2) +
      scale_x_date(expand = c(0,0), date_labels = "%b/%y", date_breaks = "30 days") +
      labs(subtitle = "Número de respondentes")
  )
  
}

```
